name: lmnh_plants_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Workflow "lint"
  lint:
    name: "Pylinting"
    runs-on: ubuntu-latest
    steps:
      - name: PyLint Init Msg
        run: 'echo "Pylint in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
        
      - name: Run PyLint
        run: pylint --fail-under=8 "*/*.py"

  # Workflow "test"
  test:
    name: "Pytesting"
    runs-on: ubuntu-latest
    steps:
      - name: PyTest Init Msg
        run: 'echo "Pytest in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run PyTest
        run: pytest -k "test"
        
