name: lmnh_plants_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Workflow "lint"
  lint:
    name: "Pylinting"
    runs-on: ubuntu-latest
    steps:
      - name: PyLint Init Msg
        run: 'echo "Pylint in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Caching dependencies
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          path: ~/cache/dependencies
          key: ${{ runner.os }}-build-${{ env.cache-name }}
  
      - name: Install dependencies
        if: steps.cache-reqs.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run PyLint
        run: pylint --fail-under=8 "*/*.py"

  # Workflow "test"
  test:
    name: "Pytesting"
    runs-on: ubuntu-latest
    steps:
      - name: PyTest Init Msg
        run: 'echo "Pytest in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Caching dependencies
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          path: ~/cache/dependencies
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          

      - name: Install dependencies
        if: steps.cache-reqs.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: pytest -k "test"
