name: lmnh_plants_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Workflow "lint"
  lint:
    name: "Code-Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Initialise PyLint
        run: 'echo "Pylint in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
        
      - name: Run PyLint
        run: pylint
